/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateSfcTaskflowV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSfcTaskflowV3Request{}

// UpdateSfcTaskflowV3Request struct for UpdateSfcTaskflowV3Request
type UpdateSfcTaskflowV3Request struct {
	// 工作流ID
	TaskflowId *string `json:"taskflowId,omitempty"`
}

// NewUpdateSfcTaskflowV3Request instantiates a new UpdateSfcTaskflowV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSfcTaskflowV3Request() *UpdateSfcTaskflowV3Request {
	this := UpdateSfcTaskflowV3Request{}
	return &this
}

// NewUpdateSfcTaskflowV3RequestWithDefaults instantiates a new UpdateSfcTaskflowV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSfcTaskflowV3RequestWithDefaults() *UpdateSfcTaskflowV3Request {
	this := UpdateSfcTaskflowV3Request{}
	return &this
}

// GetTaskflowId returns the TaskflowId field value if set, zero value otherwise.
func (o *UpdateSfcTaskflowV3Request) GetTaskflowId() string {
	if o == nil || IsNil(o.TaskflowId) {
		var ret string
		return ret
	}
	return *o.TaskflowId
}

// GetTaskflowIdOk returns a tuple with the TaskflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSfcTaskflowV3Request) GetTaskflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskflowId) {
		return nil, false
	}
	return o.TaskflowId, true
}

// HasTaskflowId returns a boolean if a field has been set.
func (o *UpdateSfcTaskflowV3Request) HasTaskflowId() bool {
	if o != nil && !IsNil(o.TaskflowId) {
		return true
	}

	return false
}

// SetTaskflowId gets a reference to the given string and assigns it to the TaskflowId field.
func (o *UpdateSfcTaskflowV3Request) SetTaskflowId(v string) {
	o.TaskflowId = &v
}

func (o UpdateSfcTaskflowV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSfcTaskflowV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskflowId) {
		toSerialize["taskflowId"] = o.TaskflowId
	}
	return toSerialize, nil
}

type NullableUpdateSfcTaskflowV3Request struct {
	value *UpdateSfcTaskflowV3Request
	isSet bool
}

func (v NullableUpdateSfcTaskflowV3Request) Get() *UpdateSfcTaskflowV3Request {
	return v.value
}

func (v *NullableUpdateSfcTaskflowV3Request) Set(val *UpdateSfcTaskflowV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSfcTaskflowV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSfcTaskflowV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSfcTaskflowV3Request(val *UpdateSfcTaskflowV3Request) *NullableUpdateSfcTaskflowV3Request {
	return &NullableUpdateSfcTaskflowV3Request{value: val, isSet: true}
}

func (v NullableUpdateSfcTaskflowV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSfcTaskflowV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


