/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostV3CollectionArchiveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3CollectionArchiveRequest{}

// PostV3CollectionArchiveRequest struct for PostV3CollectionArchiveRequest
type PostV3CollectionArchiveRequest struct {
	// 项目ID
	ProjectId *string `json:"projectId,omitempty"`
	// 归属父文件夹 ID，不提供则默认创建顶级文件夹
	ParentId *string `json:"parentId,omitempty"`
}

// NewPostV3CollectionArchiveRequest instantiates a new PostV3CollectionArchiveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3CollectionArchiveRequest() *PostV3CollectionArchiveRequest {
	this := PostV3CollectionArchiveRequest{}
	return &this
}

// NewPostV3CollectionArchiveRequestWithDefaults instantiates a new PostV3CollectionArchiveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3CollectionArchiveRequestWithDefaults() *PostV3CollectionArchiveRequest {
	this := PostV3CollectionArchiveRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *PostV3CollectionArchiveRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3CollectionArchiveRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *PostV3CollectionArchiveRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *PostV3CollectionArchiveRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *PostV3CollectionArchiveRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3CollectionArchiveRequest) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *PostV3CollectionArchiveRequest) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *PostV3CollectionArchiveRequest) SetParentId(v string) {
	o.ParentId = &v
}

func (o PostV3CollectionArchiveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3CollectionArchiveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	return toSerialize, nil
}

type NullablePostV3CollectionArchiveRequest struct {
	value *PostV3CollectionArchiveRequest
	isSet bool
}

func (v NullablePostV3CollectionArchiveRequest) Get() *PostV3CollectionArchiveRequest {
	return v.value
}

func (v *NullablePostV3CollectionArchiveRequest) Set(val *PostV3CollectionArchiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3CollectionArchiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3CollectionArchiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3CollectionArchiveRequest(val *PostV3CollectionArchiveRequest) *NullablePostV3CollectionArchiveRequest {
	return &NullablePostV3CollectionArchiveRequest{value: val, isSet: true}
}

func (v NullablePostV3CollectionArchiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3CollectionArchiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


