/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateTaskGroupTitleV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTaskGroupTitleV3Request{}

// UpdateTaskGroupTitleV3Request struct for UpdateTaskGroupTitleV3Request
type UpdateTaskGroupTitleV3Request struct {
	// 任务分组名称
	Title *string `json:"title,omitempty"`
}

// NewUpdateTaskGroupTitleV3Request instantiates a new UpdateTaskGroupTitleV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTaskGroupTitleV3Request() *UpdateTaskGroupTitleV3Request {
	this := UpdateTaskGroupTitleV3Request{}
	return &this
}

// NewUpdateTaskGroupTitleV3RequestWithDefaults instantiates a new UpdateTaskGroupTitleV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTaskGroupTitleV3RequestWithDefaults() *UpdateTaskGroupTitleV3Request {
	this := UpdateTaskGroupTitleV3Request{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateTaskGroupTitleV3Request) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTaskGroupTitleV3Request) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateTaskGroupTitleV3Request) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateTaskGroupTitleV3Request) SetTitle(v string) {
	o.Title = &v
}

func (o UpdateTaskGroupTitleV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTaskGroupTitleV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableUpdateTaskGroupTitleV3Request struct {
	value *UpdateTaskGroupTitleV3Request
	isSet bool
}

func (v NullableUpdateTaskGroupTitleV3Request) Get() *UpdateTaskGroupTitleV3Request {
	return v.value
}

func (v *NullableUpdateTaskGroupTitleV3Request) Set(val *UpdateTaskGroupTitleV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTaskGroupTitleV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTaskGroupTitleV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTaskGroupTitleV3Request(val *UpdateTaskGroupTitleV3Request) *NullableUpdateTaskGroupTitleV3Request {
	return &NullableUpdateTaskGroupTitleV3Request{value: val, isSet: true}
}

func (v NullableUpdateTaskGroupTitleV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTaskGroupTitleV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


