/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateProjectTemplateInfoV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProjectTemplateInfoV3Request{}

// UpdateProjectTemplateInfoV3Request struct for UpdateProjectTemplateInfoV3Request
type UpdateProjectTemplateInfoV3Request struct {
	// 项目模板名称
	Name *string `json:"name,omitempty"`
	// 项目模板描述
	Description *string `json:"description,omitempty"`
	// 项目模板 logo 地址
	Logo *string `json:"logo,omitempty"`
}

// NewUpdateProjectTemplateInfoV3Request instantiates a new UpdateProjectTemplateInfoV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProjectTemplateInfoV3Request() *UpdateProjectTemplateInfoV3Request {
	this := UpdateProjectTemplateInfoV3Request{}
	return &this
}

// NewUpdateProjectTemplateInfoV3RequestWithDefaults instantiates a new UpdateProjectTemplateInfoV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProjectTemplateInfoV3RequestWithDefaults() *UpdateProjectTemplateInfoV3Request {
	this := UpdateProjectTemplateInfoV3Request{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateProjectTemplateInfoV3Request) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTemplateInfoV3Request) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateProjectTemplateInfoV3Request) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateProjectTemplateInfoV3Request) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateProjectTemplateInfoV3Request) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTemplateInfoV3Request) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateProjectTemplateInfoV3Request) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateProjectTemplateInfoV3Request) SetDescription(v string) {
	o.Description = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *UpdateProjectTemplateInfoV3Request) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTemplateInfoV3Request) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *UpdateProjectTemplateInfoV3Request) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *UpdateProjectTemplateInfoV3Request) SetLogo(v string) {
	o.Logo = &v
}

func (o UpdateProjectTemplateInfoV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProjectTemplateInfoV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	return toSerialize, nil
}

type NullableUpdateProjectTemplateInfoV3Request struct {
	value *UpdateProjectTemplateInfoV3Request
	isSet bool
}

func (v NullableUpdateProjectTemplateInfoV3Request) Get() *UpdateProjectTemplateInfoV3Request {
	return v.value
}

func (v *NullableUpdateProjectTemplateInfoV3Request) Set(val *UpdateProjectTemplateInfoV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProjectTemplateInfoV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProjectTemplateInfoV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProjectTemplateInfoV3Request(val *UpdateProjectTemplateInfoV3Request) *NullableUpdateProjectTemplateInfoV3Request {
	return &NullableUpdateProjectTemplateInfoV3Request{value: val, isSet: true}
}

func (v NullableUpdateProjectTemplateInfoV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProjectTemplateInfoV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


