/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTaskLinkV3RequestLinkedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTaskLinkV3RequestLinkedData{}

// CreateTaskLinkV3RequestLinkedData 关联网页
type CreateTaskLinkV3RequestLinkedData struct {
	// 外部关联的子类型,支持'web'和'dingtalk-doc',默认为'web'
	SubType *string `json:"subType,omitempty"`
	// 标题
	Title *string `json:"title,omitempty"`
	// 内容
	Content *string `json:"content,omitempty"`
	// 链接
	Url *string `json:"url,omitempty"`
	// 缩略图
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`
	// 额外数据, JSONString格式, 例如 {\"subType\": \"dingtalk-doc\"}
	MetaString *string `json:"metaString,omitempty"`
}

// NewCreateTaskLinkV3RequestLinkedData instantiates a new CreateTaskLinkV3RequestLinkedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTaskLinkV3RequestLinkedData() *CreateTaskLinkV3RequestLinkedData {
	this := CreateTaskLinkV3RequestLinkedData{}
	return &this
}

// NewCreateTaskLinkV3RequestLinkedDataWithDefaults instantiates a new CreateTaskLinkV3RequestLinkedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTaskLinkV3RequestLinkedDataWithDefaults() *CreateTaskLinkV3RequestLinkedData {
	this := CreateTaskLinkV3RequestLinkedData{}
	return &this
}

// GetSubType returns the SubType field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetSubType() string {
	if o == nil || IsNil(o.SubType) {
		var ret string
		return ret
	}
	return *o.SubType
}

// GetSubTypeOk returns a tuple with the SubType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetSubTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SubType) {
		return nil, false
	}
	return o.SubType, true
}

// HasSubType returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasSubType() bool {
	if o != nil && !IsNil(o.SubType) {
		return true
	}

	return false
}

// SetSubType gets a reference to the given string and assigns it to the SubType field.
func (o *CreateTaskLinkV3RequestLinkedData) SetSubType(v string) {
	o.SubType = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateTaskLinkV3RequestLinkedData) SetTitle(v string) {
	o.Title = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *CreateTaskLinkV3RequestLinkedData) SetContent(v string) {
	o.Content = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CreateTaskLinkV3RequestLinkedData) SetUrl(v string) {
	o.Url = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetThumbnailUrl() string {
	if o == nil || IsNil(o.ThumbnailUrl) {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailUrl) {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasThumbnailUrl() bool {
	if o != nil && !IsNil(o.ThumbnailUrl) {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *CreateTaskLinkV3RequestLinkedData) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetMetaString returns the MetaString field value if set, zero value otherwise.
func (o *CreateTaskLinkV3RequestLinkedData) GetMetaString() string {
	if o == nil || IsNil(o.MetaString) {
		var ret string
		return ret
	}
	return *o.MetaString
}

// GetMetaStringOk returns a tuple with the MetaString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTaskLinkV3RequestLinkedData) GetMetaStringOk() (*string, bool) {
	if o == nil || IsNil(o.MetaString) {
		return nil, false
	}
	return o.MetaString, true
}

// HasMetaString returns a boolean if a field has been set.
func (o *CreateTaskLinkV3RequestLinkedData) HasMetaString() bool {
	if o != nil && !IsNil(o.MetaString) {
		return true
	}

	return false
}

// SetMetaString gets a reference to the given string and assigns it to the MetaString field.
func (o *CreateTaskLinkV3RequestLinkedData) SetMetaString(v string) {
	o.MetaString = &v
}

func (o CreateTaskLinkV3RequestLinkedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTaskLinkV3RequestLinkedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubType) {
		toSerialize["subType"] = o.SubType
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.ThumbnailUrl) {
		toSerialize["thumbnailUrl"] = o.ThumbnailUrl
	}
	if !IsNil(o.MetaString) {
		toSerialize["metaString"] = o.MetaString
	}
	return toSerialize, nil
}

type NullableCreateTaskLinkV3RequestLinkedData struct {
	value *CreateTaskLinkV3RequestLinkedData
	isSet bool
}

func (v NullableCreateTaskLinkV3RequestLinkedData) Get() *CreateTaskLinkV3RequestLinkedData {
	return v.value
}

func (v *NullableCreateTaskLinkV3RequestLinkedData) Set(val *CreateTaskLinkV3RequestLinkedData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTaskLinkV3RequestLinkedData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTaskLinkV3RequestLinkedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTaskLinkV3RequestLinkedData(val *CreateTaskLinkV3RequestLinkedData) *NullableCreateTaskLinkV3RequestLinkedData {
	return &NullableCreateTaskLinkV3RequestLinkedData{value: val, isSet: true}
}

func (v NullableCreateTaskLinkV3RequestLinkedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTaskLinkV3RequestLinkedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


