/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostV3ProjectplanProjectPlansRequestMemberSyncRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3ProjectplanProjectPlansRequestMemberSyncRule{}

// PostV3ProjectplanProjectPlansRequestMemberSyncRule struct for PostV3ProjectplanProjectPlansRequestMemberSyncRule
type PostV3ProjectplanProjectPlansRequestMemberSyncRule struct {
	// 是否同步任务执行者至计划参与者
	IsSyncTaskExecuteToInvolves *bool `json:"isSyncTaskExecuteToInvolves,omitempty"`
	// 是否同步子计划管理员至计划参与者
	IsSyncSubAdminToInvolves *bool `json:"isSyncSubAdminToInvolves,omitempty"`
	// 是否同步子计划参与者至计划参与者
	IsSyncSubInvolvesToInvolves *bool `json:"isSyncSubInvolvesToInvolves,omitempty"`
}

// NewPostV3ProjectplanProjectPlansRequestMemberSyncRule instantiates a new PostV3ProjectplanProjectPlansRequestMemberSyncRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3ProjectplanProjectPlansRequestMemberSyncRule() *PostV3ProjectplanProjectPlansRequestMemberSyncRule {
	this := PostV3ProjectplanProjectPlansRequestMemberSyncRule{}
	return &this
}

// NewPostV3ProjectplanProjectPlansRequestMemberSyncRuleWithDefaults instantiates a new PostV3ProjectplanProjectPlansRequestMemberSyncRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3ProjectplanProjectPlansRequestMemberSyncRuleWithDefaults() *PostV3ProjectplanProjectPlansRequestMemberSyncRule {
	this := PostV3ProjectplanProjectPlansRequestMemberSyncRule{}
	return &this
}

// GetIsSyncTaskExecuteToInvolves returns the IsSyncTaskExecuteToInvolves field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncTaskExecuteToInvolves() bool {
	if o == nil || IsNil(o.IsSyncTaskExecuteToInvolves) {
		var ret bool
		return ret
	}
	return *o.IsSyncTaskExecuteToInvolves
}

// GetIsSyncTaskExecuteToInvolvesOk returns a tuple with the IsSyncTaskExecuteToInvolves field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncTaskExecuteToInvolvesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSyncTaskExecuteToInvolves) {
		return nil, false
	}
	return o.IsSyncTaskExecuteToInvolves, true
}

// HasIsSyncTaskExecuteToInvolves returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) HasIsSyncTaskExecuteToInvolves() bool {
	if o != nil && !IsNil(o.IsSyncTaskExecuteToInvolves) {
		return true
	}

	return false
}

// SetIsSyncTaskExecuteToInvolves gets a reference to the given bool and assigns it to the IsSyncTaskExecuteToInvolves field.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) SetIsSyncTaskExecuteToInvolves(v bool) {
	o.IsSyncTaskExecuteToInvolves = &v
}

// GetIsSyncSubAdminToInvolves returns the IsSyncSubAdminToInvolves field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncSubAdminToInvolves() bool {
	if o == nil || IsNil(o.IsSyncSubAdminToInvolves) {
		var ret bool
		return ret
	}
	return *o.IsSyncSubAdminToInvolves
}

// GetIsSyncSubAdminToInvolvesOk returns a tuple with the IsSyncSubAdminToInvolves field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncSubAdminToInvolvesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSyncSubAdminToInvolves) {
		return nil, false
	}
	return o.IsSyncSubAdminToInvolves, true
}

// HasIsSyncSubAdminToInvolves returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) HasIsSyncSubAdminToInvolves() bool {
	if o != nil && !IsNil(o.IsSyncSubAdminToInvolves) {
		return true
	}

	return false
}

// SetIsSyncSubAdminToInvolves gets a reference to the given bool and assigns it to the IsSyncSubAdminToInvolves field.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) SetIsSyncSubAdminToInvolves(v bool) {
	o.IsSyncSubAdminToInvolves = &v
}

// GetIsSyncSubInvolvesToInvolves returns the IsSyncSubInvolvesToInvolves field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncSubInvolvesToInvolves() bool {
	if o == nil || IsNil(o.IsSyncSubInvolvesToInvolves) {
		var ret bool
		return ret
	}
	return *o.IsSyncSubInvolvesToInvolves
}

// GetIsSyncSubInvolvesToInvolvesOk returns a tuple with the IsSyncSubInvolvesToInvolves field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) GetIsSyncSubInvolvesToInvolvesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSyncSubInvolvesToInvolves) {
		return nil, false
	}
	return o.IsSyncSubInvolvesToInvolves, true
}

// HasIsSyncSubInvolvesToInvolves returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) HasIsSyncSubInvolvesToInvolves() bool {
	if o != nil && !IsNil(o.IsSyncSubInvolvesToInvolves) {
		return true
	}

	return false
}

// SetIsSyncSubInvolvesToInvolves gets a reference to the given bool and assigns it to the IsSyncSubInvolvesToInvolves field.
func (o *PostV3ProjectplanProjectPlansRequestMemberSyncRule) SetIsSyncSubInvolvesToInvolves(v bool) {
	o.IsSyncSubInvolvesToInvolves = &v
}

func (o PostV3ProjectplanProjectPlansRequestMemberSyncRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3ProjectplanProjectPlansRequestMemberSyncRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsSyncTaskExecuteToInvolves) {
		toSerialize["isSyncTaskExecuteToInvolves"] = o.IsSyncTaskExecuteToInvolves
	}
	if !IsNil(o.IsSyncSubAdminToInvolves) {
		toSerialize["isSyncSubAdminToInvolves"] = o.IsSyncSubAdminToInvolves
	}
	if !IsNil(o.IsSyncSubInvolvesToInvolves) {
		toSerialize["isSyncSubInvolvesToInvolves"] = o.IsSyncSubInvolvesToInvolves
	}
	return toSerialize, nil
}

type NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule struct {
	value *PostV3ProjectplanProjectPlansRequestMemberSyncRule
	isSet bool
}

func (v NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) Get() *PostV3ProjectplanProjectPlansRequestMemberSyncRule {
	return v.value
}

func (v *NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) Set(val *PostV3ProjectplanProjectPlansRequestMemberSyncRule) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3ProjectplanProjectPlansRequestMemberSyncRule(val *PostV3ProjectplanProjectPlansRequestMemberSyncRule) *NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule {
	return &NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule{value: val, isSet: true}
}

func (v NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3ProjectplanProjectPlansRequestMemberSyncRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


