/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateStatusExecutorsV3RequestDelInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStatusExecutorsV3RequestDelInner{}

// UpdateStatusExecutorsV3RequestDelInner 
type UpdateStatusExecutorsV3RequestDelInner struct {
	// 用户ID 或者 角色ID 或者 任务执行者 或者 任务创建者
	SubjectId *string `json:"subjectId,omitempty"`
	// 用户 或者 橘色 或者 任务角色
	SubjectType *string `json:"subjectType,omitempty"`
}

// NewUpdateStatusExecutorsV3RequestDelInner instantiates a new UpdateStatusExecutorsV3RequestDelInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStatusExecutorsV3RequestDelInner() *UpdateStatusExecutorsV3RequestDelInner {
	this := UpdateStatusExecutorsV3RequestDelInner{}
	return &this
}

// NewUpdateStatusExecutorsV3RequestDelInnerWithDefaults instantiates a new UpdateStatusExecutorsV3RequestDelInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStatusExecutorsV3RequestDelInnerWithDefaults() *UpdateStatusExecutorsV3RequestDelInner {
	this := UpdateStatusExecutorsV3RequestDelInner{}
	return &this
}

// GetSubjectId returns the SubjectId field value if set, zero value otherwise.
func (o *UpdateStatusExecutorsV3RequestDelInner) GetSubjectId() string {
	if o == nil || IsNil(o.SubjectId) {
		var ret string
		return ret
	}
	return *o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStatusExecutorsV3RequestDelInner) GetSubjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubjectId) {
		return nil, false
	}
	return o.SubjectId, true
}

// HasSubjectId returns a boolean if a field has been set.
func (o *UpdateStatusExecutorsV3RequestDelInner) HasSubjectId() bool {
	if o != nil && !IsNil(o.SubjectId) {
		return true
	}

	return false
}

// SetSubjectId gets a reference to the given string and assigns it to the SubjectId field.
func (o *UpdateStatusExecutorsV3RequestDelInner) SetSubjectId(v string) {
	o.SubjectId = &v
}

// GetSubjectType returns the SubjectType field value if set, zero value otherwise.
func (o *UpdateStatusExecutorsV3RequestDelInner) GetSubjectType() string {
	if o == nil || IsNil(o.SubjectType) {
		var ret string
		return ret
	}
	return *o.SubjectType
}

// GetSubjectTypeOk returns a tuple with the SubjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStatusExecutorsV3RequestDelInner) GetSubjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SubjectType) {
		return nil, false
	}
	return o.SubjectType, true
}

// HasSubjectType returns a boolean if a field has been set.
func (o *UpdateStatusExecutorsV3RequestDelInner) HasSubjectType() bool {
	if o != nil && !IsNil(o.SubjectType) {
		return true
	}

	return false
}

// SetSubjectType gets a reference to the given string and assigns it to the SubjectType field.
func (o *UpdateStatusExecutorsV3RequestDelInner) SetSubjectType(v string) {
	o.SubjectType = &v
}

func (o UpdateStatusExecutorsV3RequestDelInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStatusExecutorsV3RequestDelInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubjectId) {
		toSerialize["subjectId"] = o.SubjectId
	}
	if !IsNil(o.SubjectType) {
		toSerialize["subjectType"] = o.SubjectType
	}
	return toSerialize, nil
}

type NullableUpdateStatusExecutorsV3RequestDelInner struct {
	value *UpdateStatusExecutorsV3RequestDelInner
	isSet bool
}

func (v NullableUpdateStatusExecutorsV3RequestDelInner) Get() *UpdateStatusExecutorsV3RequestDelInner {
	return v.value
}

func (v *NullableUpdateStatusExecutorsV3RequestDelInner) Set(val *UpdateStatusExecutorsV3RequestDelInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStatusExecutorsV3RequestDelInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStatusExecutorsV3RequestDelInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStatusExecutorsV3RequestDelInner(val *UpdateStatusExecutorsV3RequestDelInner) *NullableUpdateStatusExecutorsV3RequestDelInner {
	return &NullableUpdateStatusExecutorsV3RequestDelInner{value: val, isSet: true}
}

func (v NullableUpdateStatusExecutorsV3RequestDelInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStatusExecutorsV3RequestDelInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


