/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateStatusCustomFieldV3RequestValueInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStatusCustomFieldV3RequestValueInner{}

// CreateStatusCustomFieldV3RequestValueInner struct for CreateStatusCustomFieldV3RequestValueInner
type CreateStatusCustomFieldV3RequestValueInner struct {
	Id *string `json:"id,omitempty"`
	// 字段值渲染值
	Title *string `json:"title,omitempty"`
	// 用户头像，仅用于成员字段
	ThumbUrl *string `json:"thumbUrl,omitempty"`
	// 自定义字段值元属性
	MetaString *string `json:"metaString,omitempty"`
}

// NewCreateStatusCustomFieldV3RequestValueInner instantiates a new CreateStatusCustomFieldV3RequestValueInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStatusCustomFieldV3RequestValueInner() *CreateStatusCustomFieldV3RequestValueInner {
	this := CreateStatusCustomFieldV3RequestValueInner{}
	return &this
}

// NewCreateStatusCustomFieldV3RequestValueInnerWithDefaults instantiates a new CreateStatusCustomFieldV3RequestValueInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStatusCustomFieldV3RequestValueInnerWithDefaults() *CreateStatusCustomFieldV3RequestValueInner {
	this := CreateStatusCustomFieldV3RequestValueInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateStatusCustomFieldV3RequestValueInner) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateStatusCustomFieldV3RequestValueInner) SetTitle(v string) {
	o.Title = &v
}

// GetThumbUrl returns the ThumbUrl field value if set, zero value otherwise.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetThumbUrl() string {
	if o == nil || IsNil(o.ThumbUrl) {
		var ret string
		return ret
	}
	return *o.ThumbUrl
}

// GetThumbUrlOk returns a tuple with the ThumbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetThumbUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbUrl) {
		return nil, false
	}
	return o.ThumbUrl, true
}

// HasThumbUrl returns a boolean if a field has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) HasThumbUrl() bool {
	if o != nil && !IsNil(o.ThumbUrl) {
		return true
	}

	return false
}

// SetThumbUrl gets a reference to the given string and assigns it to the ThumbUrl field.
func (o *CreateStatusCustomFieldV3RequestValueInner) SetThumbUrl(v string) {
	o.ThumbUrl = &v
}

// GetMetaString returns the MetaString field value if set, zero value otherwise.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetMetaString() string {
	if o == nil || IsNil(o.MetaString) {
		var ret string
		return ret
	}
	return *o.MetaString
}

// GetMetaStringOk returns a tuple with the MetaString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) GetMetaStringOk() (*string, bool) {
	if o == nil || IsNil(o.MetaString) {
		return nil, false
	}
	return o.MetaString, true
}

// HasMetaString returns a boolean if a field has been set.
func (o *CreateStatusCustomFieldV3RequestValueInner) HasMetaString() bool {
	if o != nil && !IsNil(o.MetaString) {
		return true
	}

	return false
}

// SetMetaString gets a reference to the given string and assigns it to the MetaString field.
func (o *CreateStatusCustomFieldV3RequestValueInner) SetMetaString(v string) {
	o.MetaString = &v
}

func (o CreateStatusCustomFieldV3RequestValueInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStatusCustomFieldV3RequestValueInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.ThumbUrl) {
		toSerialize["thumbUrl"] = o.ThumbUrl
	}
	if !IsNil(o.MetaString) {
		toSerialize["metaString"] = o.MetaString
	}
	return toSerialize, nil
}

type NullableCreateStatusCustomFieldV3RequestValueInner struct {
	value *CreateStatusCustomFieldV3RequestValueInner
	isSet bool
}

func (v NullableCreateStatusCustomFieldV3RequestValueInner) Get() *CreateStatusCustomFieldV3RequestValueInner {
	return v.value
}

func (v *NullableCreateStatusCustomFieldV3RequestValueInner) Set(val *CreateStatusCustomFieldV3RequestValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStatusCustomFieldV3RequestValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStatusCustomFieldV3RequestValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStatusCustomFieldV3RequestValueInner(val *CreateStatusCustomFieldV3RequestValueInner) *NullableCreateStatusCustomFieldV3RequestValueInner {
	return &NullableCreateStatusCustomFieldV3RequestValueInner{value: val, isSet: true}
}

func (v NullableCreateStatusCustomFieldV3RequestValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStatusCustomFieldV3RequestValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


