/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateProjectTemplateV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectTemplateV3Request{}

// CreateProjectTemplateV3Request 创建项目模版请求
type CreateProjectTemplateV3Request struct {
	// 模板名称
	Name *string `json:"name,omitempty"`
	// 创建项目模版的源项目 ID
	ProjectId *string `json:"projectId,omitempty"`
	// 模板描述
	Description *string `json:"description,omitempty"`
	// 模板 logo 地址
	Logo *string `json:"logo,omitempty"`
	// 模板分类列表
	Labels []string `json:"labels,omitempty"`
}

// NewCreateProjectTemplateV3Request instantiates a new CreateProjectTemplateV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectTemplateV3Request() *CreateProjectTemplateV3Request {
	this := CreateProjectTemplateV3Request{}
	return &this
}

// NewCreateProjectTemplateV3RequestWithDefaults instantiates a new CreateProjectTemplateV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectTemplateV3RequestWithDefaults() *CreateProjectTemplateV3Request {
	this := CreateProjectTemplateV3Request{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateProjectTemplateV3Request) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectTemplateV3Request) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateProjectTemplateV3Request) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateProjectTemplateV3Request) SetName(v string) {
	o.Name = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreateProjectTemplateV3Request) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectTemplateV3Request) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreateProjectTemplateV3Request) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CreateProjectTemplateV3Request) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateProjectTemplateV3Request) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectTemplateV3Request) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateProjectTemplateV3Request) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateProjectTemplateV3Request) SetDescription(v string) {
	o.Description = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *CreateProjectTemplateV3Request) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectTemplateV3Request) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *CreateProjectTemplateV3Request) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *CreateProjectTemplateV3Request) SetLogo(v string) {
	o.Logo = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateProjectTemplateV3Request) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectTemplateV3Request) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateProjectTemplateV3Request) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *CreateProjectTemplateV3Request) SetLabels(v []string) {
	o.Labels = v
}

func (o CreateProjectTemplateV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectTemplateV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableCreateProjectTemplateV3Request struct {
	value *CreateProjectTemplateV3Request
	isSet bool
}

func (v NullableCreateProjectTemplateV3Request) Get() *CreateProjectTemplateV3Request {
	return v.value
}

func (v *NullableCreateProjectTemplateV3Request) Set(val *CreateProjectTemplateV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectTemplateV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectTemplateV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectTemplateV3Request(val *CreateProjectTemplateV3Request) *NullableCreateProjectTemplateV3Request {
	return &NullableCreateProjectTemplateV3Request{value: val, isSet: true}
}

func (v NullableCreateProjectTemplateV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectTemplateV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


