/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateOrgRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrgRoleResponse{}

// CreateOrgRoleResponse 
type CreateOrgRoleResponse struct {
	Result interface{} `json:"result,omitempty"`
	// 响应状态码
	Code *float32 `json:"code,omitempty"`
	// 异常错误信息
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// 请求 ID，请求异常时可提供此 ID，进行问题排查。
	RequestId *string `json:"requestId,omitempty"`
}

// NewCreateOrgRoleResponse instantiates a new CreateOrgRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrgRoleResponse() *CreateOrgRoleResponse {
	this := CreateOrgRoleResponse{}
	return &this
}

// NewCreateOrgRoleResponseWithDefaults instantiates a new CreateOrgRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrgRoleResponseWithDefaults() *CreateOrgRoleResponse {
	this := CreateOrgRoleResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrgRoleResponse) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrgRoleResponse) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CreateOrgRoleResponse) HasResult() bool {
	if o != nil && IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given interface{} and assigns it to the Result field.
func (o *CreateOrgRoleResponse) SetResult(v interface{}) {
	o.Result = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateOrgRoleResponse) GetCode() float32 {
	if o == nil || IsNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgRoleResponse) GetCodeOk() (*float32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateOrgRoleResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *CreateOrgRoleResponse) SetCode(v float32) {
	o.Code = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *CreateOrgRoleResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgRoleResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *CreateOrgRoleResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *CreateOrgRoleResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateOrgRoleResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgRoleResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateOrgRoleResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateOrgRoleResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CreateOrgRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrgRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCreateOrgRoleResponse struct {
	value *CreateOrgRoleResponse
	isSet bool
}

func (v NullableCreateOrgRoleResponse) Get() *CreateOrgRoleResponse {
	return v.value
}

func (v *NullableCreateOrgRoleResponse) Set(val *CreateOrgRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrgRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrgRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrgRoleResponse(val *CreateOrgRoleResponse) *NullableCreateOrgRoleResponse {
	return &NullableCreateOrgRoleResponse{value: val, isSet: true}
}

func (v NullableCreateOrgRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrgRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


