/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdatePlanApprovalV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlanApprovalV3Request{}

// UpdatePlanApprovalV3Request struct for UpdatePlanApprovalV3Request
type UpdatePlanApprovalV3Request struct {
	ApproveInfo *UpdatePlanApprovalV3RequestApproveInfo `json:"approveInfo,omitempty"`
}

// NewUpdatePlanApprovalV3Request instantiates a new UpdatePlanApprovalV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlanApprovalV3Request() *UpdatePlanApprovalV3Request {
	this := UpdatePlanApprovalV3Request{}
	return &this
}

// NewUpdatePlanApprovalV3RequestWithDefaults instantiates a new UpdatePlanApprovalV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlanApprovalV3RequestWithDefaults() *UpdatePlanApprovalV3Request {
	this := UpdatePlanApprovalV3Request{}
	return &this
}

// GetApproveInfo returns the ApproveInfo field value if set, zero value otherwise.
func (o *UpdatePlanApprovalV3Request) GetApproveInfo() UpdatePlanApprovalV3RequestApproveInfo {
	if o == nil || IsNil(o.ApproveInfo) {
		var ret UpdatePlanApprovalV3RequestApproveInfo
		return ret
	}
	return *o.ApproveInfo
}

// GetApproveInfoOk returns a tuple with the ApproveInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlanApprovalV3Request) GetApproveInfoOk() (*UpdatePlanApprovalV3RequestApproveInfo, bool) {
	if o == nil || IsNil(o.ApproveInfo) {
		return nil, false
	}
	return o.ApproveInfo, true
}

// HasApproveInfo returns a boolean if a field has been set.
func (o *UpdatePlanApprovalV3Request) HasApproveInfo() bool {
	if o != nil && !IsNil(o.ApproveInfo) {
		return true
	}

	return false
}

// SetApproveInfo gets a reference to the given UpdatePlanApprovalV3RequestApproveInfo and assigns it to the ApproveInfo field.
func (o *UpdatePlanApprovalV3Request) SetApproveInfo(v UpdatePlanApprovalV3RequestApproveInfo) {
	o.ApproveInfo = &v
}

func (o UpdatePlanApprovalV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlanApprovalV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApproveInfo) {
		toSerialize["approveInfo"] = o.ApproveInfo
	}
	return toSerialize, nil
}

type NullableUpdatePlanApprovalV3Request struct {
	value *UpdatePlanApprovalV3Request
	isSet bool
}

func (v NullableUpdatePlanApprovalV3Request) Get() *UpdatePlanApprovalV3Request {
	return v.value
}

func (v *NullableUpdatePlanApprovalV3Request) Set(val *UpdatePlanApprovalV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlanApprovalV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlanApprovalV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlanApprovalV3Request(val *UpdatePlanApprovalV3Request) *NullableUpdatePlanApprovalV3Request {
	return &NullableUpdatePlanApprovalV3Request{value: val, isSet: true}
}

func (v NullableUpdatePlanApprovalV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlanApprovalV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


