/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateBaselineRequestPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBaselineRequestPayload{}

// UpdateBaselineRequestPayload 基线数据
type UpdateBaselineRequestPayload struct {
	// 如果是实时字段对比型基线，则返回开始时间对比字段
	StartDateCompareField *string `json:"startDateCompareField,omitempty"`
	// 如果是实时字段对比型基线，则返回截止时间对比字段
	DueDateCompareField *string `json:"dueDateCompareField,omitempty"`
	// 基线审批状态
	ApprovalStatus *string `json:"approvalStatus,omitempty"`
	// 基线审批链接
	ApprovalUrl *string `json:"approvalUrl,omitempty"`
	// 基线锁(当为true时，不能更新基线名称)
	Lock *bool `json:"lock,omitempty"`
}

// NewUpdateBaselineRequestPayload instantiates a new UpdateBaselineRequestPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBaselineRequestPayload() *UpdateBaselineRequestPayload {
	this := UpdateBaselineRequestPayload{}
	return &this
}

// NewUpdateBaselineRequestPayloadWithDefaults instantiates a new UpdateBaselineRequestPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBaselineRequestPayloadWithDefaults() *UpdateBaselineRequestPayload {
	this := UpdateBaselineRequestPayload{}
	return &this
}

// GetStartDateCompareField returns the StartDateCompareField field value if set, zero value otherwise.
func (o *UpdateBaselineRequestPayload) GetStartDateCompareField() string {
	if o == nil || IsNil(o.StartDateCompareField) {
		var ret string
		return ret
	}
	return *o.StartDateCompareField
}

// GetStartDateCompareFieldOk returns a tuple with the StartDateCompareField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBaselineRequestPayload) GetStartDateCompareFieldOk() (*string, bool) {
	if o == nil || IsNil(o.StartDateCompareField) {
		return nil, false
	}
	return o.StartDateCompareField, true
}

// HasStartDateCompareField returns a boolean if a field has been set.
func (o *UpdateBaselineRequestPayload) HasStartDateCompareField() bool {
	if o != nil && !IsNil(o.StartDateCompareField) {
		return true
	}

	return false
}

// SetStartDateCompareField gets a reference to the given string and assigns it to the StartDateCompareField field.
func (o *UpdateBaselineRequestPayload) SetStartDateCompareField(v string) {
	o.StartDateCompareField = &v
}

// GetDueDateCompareField returns the DueDateCompareField field value if set, zero value otherwise.
func (o *UpdateBaselineRequestPayload) GetDueDateCompareField() string {
	if o == nil || IsNil(o.DueDateCompareField) {
		var ret string
		return ret
	}
	return *o.DueDateCompareField
}

// GetDueDateCompareFieldOk returns a tuple with the DueDateCompareField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBaselineRequestPayload) GetDueDateCompareFieldOk() (*string, bool) {
	if o == nil || IsNil(o.DueDateCompareField) {
		return nil, false
	}
	return o.DueDateCompareField, true
}

// HasDueDateCompareField returns a boolean if a field has been set.
func (o *UpdateBaselineRequestPayload) HasDueDateCompareField() bool {
	if o != nil && !IsNil(o.DueDateCompareField) {
		return true
	}

	return false
}

// SetDueDateCompareField gets a reference to the given string and assigns it to the DueDateCompareField field.
func (o *UpdateBaselineRequestPayload) SetDueDateCompareField(v string) {
	o.DueDateCompareField = &v
}

// GetApprovalStatus returns the ApprovalStatus field value if set, zero value otherwise.
func (o *UpdateBaselineRequestPayload) GetApprovalStatus() string {
	if o == nil || IsNil(o.ApprovalStatus) {
		var ret string
		return ret
	}
	return *o.ApprovalStatus
}

// GetApprovalStatusOk returns a tuple with the ApprovalStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBaselineRequestPayload) GetApprovalStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalStatus) {
		return nil, false
	}
	return o.ApprovalStatus, true
}

// HasApprovalStatus returns a boolean if a field has been set.
func (o *UpdateBaselineRequestPayload) HasApprovalStatus() bool {
	if o != nil && !IsNil(o.ApprovalStatus) {
		return true
	}

	return false
}

// SetApprovalStatus gets a reference to the given string and assigns it to the ApprovalStatus field.
func (o *UpdateBaselineRequestPayload) SetApprovalStatus(v string) {
	o.ApprovalStatus = &v
}

// GetApprovalUrl returns the ApprovalUrl field value if set, zero value otherwise.
func (o *UpdateBaselineRequestPayload) GetApprovalUrl() string {
	if o == nil || IsNil(o.ApprovalUrl) {
		var ret string
		return ret
	}
	return *o.ApprovalUrl
}

// GetApprovalUrlOk returns a tuple with the ApprovalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBaselineRequestPayload) GetApprovalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalUrl) {
		return nil, false
	}
	return o.ApprovalUrl, true
}

// HasApprovalUrl returns a boolean if a field has been set.
func (o *UpdateBaselineRequestPayload) HasApprovalUrl() bool {
	if o != nil && !IsNil(o.ApprovalUrl) {
		return true
	}

	return false
}

// SetApprovalUrl gets a reference to the given string and assigns it to the ApprovalUrl field.
func (o *UpdateBaselineRequestPayload) SetApprovalUrl(v string) {
	o.ApprovalUrl = &v
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *UpdateBaselineRequestPayload) GetLock() bool {
	if o == nil || IsNil(o.Lock) {
		var ret bool
		return ret
	}
	return *o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBaselineRequestPayload) GetLockOk() (*bool, bool) {
	if o == nil || IsNil(o.Lock) {
		return nil, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *UpdateBaselineRequestPayload) HasLock() bool {
	if o != nil && !IsNil(o.Lock) {
		return true
	}

	return false
}

// SetLock gets a reference to the given bool and assigns it to the Lock field.
func (o *UpdateBaselineRequestPayload) SetLock(v bool) {
	o.Lock = &v
}

func (o UpdateBaselineRequestPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBaselineRequestPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartDateCompareField) {
		toSerialize["startDateCompareField"] = o.StartDateCompareField
	}
	if !IsNil(o.DueDateCompareField) {
		toSerialize["dueDateCompareField"] = o.DueDateCompareField
	}
	if !IsNil(o.ApprovalStatus) {
		toSerialize["approvalStatus"] = o.ApprovalStatus
	}
	if !IsNil(o.ApprovalUrl) {
		toSerialize["approvalUrl"] = o.ApprovalUrl
	}
	if !IsNil(o.Lock) {
		toSerialize["lock"] = o.Lock
	}
	return toSerialize, nil
}

type NullableUpdateBaselineRequestPayload struct {
	value *UpdateBaselineRequestPayload
	isSet bool
}

func (v NullableUpdateBaselineRequestPayload) Get() *UpdateBaselineRequestPayload {
	return v.value
}

func (v *NullableUpdateBaselineRequestPayload) Set(val *UpdateBaselineRequestPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBaselineRequestPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBaselineRequestPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBaselineRequestPayload(val *UpdateBaselineRequestPayload) *NullableUpdateBaselineRequestPayload {
	return &NullableUpdateBaselineRequestPayload{value: val, isSet: true}
}

func (v NullableUpdateBaselineRequestPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBaselineRequestPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


