/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateProjectTableCustomFieldRequestActionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProjectTableCustomFieldRequestActionsInner{}

// UpdateProjectTableCustomFieldRequestActionsInner struct for UpdateProjectTableCustomFieldRequestActionsInner
type UpdateProjectTableCustomFieldRequestActionsInner struct {
	// - addRow:       新增行 - removeRow:    删除行 - removeRowAll: 删除所有行 - updateRow:    更新行 - updateCell:   更新单元格 - clearCell:    清空单元格 - clearRow:     清空行 
	Action string `json:"action"`
	// 行号, 0 表示第一行, 多个action组合时，行号按前一次操作结果计算
	RowNumber *float32 `json:"rowNumber,omitempty"`
	// 字段的表头ID，更新单元格时，和 headerName 二选一
	HeaderId *string `json:"headerId,omitempty"`
	// 字段的表头名，如果有重复表头，只更新第一个，和 headerId 二选一
	HeaderName *string `json:"headerName,omitempty"`
	From *UpdateProjectTableCustomFieldRequestActionsInnerFrom `json:"from,omitempty"`
	// 单元格的值
	Value *string `json:"value,omitempty"`
	// 新增/更新行，并且设置该行的值，适用于 addRow, updateRow 例如: { action:addRow, values=['1','2'] } 
	Values []string `json:"values,omitempty"`
	// 键值对表达 values, 字符串格式 例如: { action:addRow, valueMapJson:'{\"headerId\": \"value1\", \"headerName\": \"value2\"}' } key 为 字段的表头ID 或者 表头名称 
	ValueMapJson *string `json:"valueMapJson,omitempty"`
}

// NewUpdateProjectTableCustomFieldRequestActionsInner instantiates a new UpdateProjectTableCustomFieldRequestActionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProjectTableCustomFieldRequestActionsInner(action string) *UpdateProjectTableCustomFieldRequestActionsInner {
	this := UpdateProjectTableCustomFieldRequestActionsInner{}
	this.Action = action
	return &this
}

// NewUpdateProjectTableCustomFieldRequestActionsInnerWithDefaults instantiates a new UpdateProjectTableCustomFieldRequestActionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProjectTableCustomFieldRequestActionsInnerWithDefaults() *UpdateProjectTableCustomFieldRequestActionsInner {
	this := UpdateProjectTableCustomFieldRequestActionsInner{}
	return &this
}

// GetAction returns the Action field value
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetAction(v string) {
	o.Action = v
}

// GetRowNumber returns the RowNumber field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetRowNumber() float32 {
	if o == nil || IsNil(o.RowNumber) {
		var ret float32
		return ret
	}
	return *o.RowNumber
}

// GetRowNumberOk returns a tuple with the RowNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetRowNumberOk() (*float32, bool) {
	if o == nil || IsNil(o.RowNumber) {
		return nil, false
	}
	return o.RowNumber, true
}

// HasRowNumber returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasRowNumber() bool {
	if o != nil && !IsNil(o.RowNumber) {
		return true
	}

	return false
}

// SetRowNumber gets a reference to the given float32 and assigns it to the RowNumber field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetRowNumber(v float32) {
	o.RowNumber = &v
}

// GetHeaderId returns the HeaderId field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetHeaderId() string {
	if o == nil || IsNil(o.HeaderId) {
		var ret string
		return ret
	}
	return *o.HeaderId
}

// GetHeaderIdOk returns a tuple with the HeaderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetHeaderIdOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderId) {
		return nil, false
	}
	return o.HeaderId, true
}

// HasHeaderId returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasHeaderId() bool {
	if o != nil && !IsNil(o.HeaderId) {
		return true
	}

	return false
}

// SetHeaderId gets a reference to the given string and assigns it to the HeaderId field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetHeaderId(v string) {
	o.HeaderId = &v
}

// GetHeaderName returns the HeaderName field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetHeaderName() string {
	if o == nil || IsNil(o.HeaderName) {
		var ret string
		return ret
	}
	return *o.HeaderName
}

// GetHeaderNameOk returns a tuple with the HeaderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetHeaderNameOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderName) {
		return nil, false
	}
	return o.HeaderName, true
}

// HasHeaderName returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasHeaderName() bool {
	if o != nil && !IsNil(o.HeaderName) {
		return true
	}

	return false
}

// SetHeaderName gets a reference to the given string and assigns it to the HeaderName field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetHeaderName(v string) {
	o.HeaderName = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetFrom() UpdateProjectTableCustomFieldRequestActionsInnerFrom {
	if o == nil || IsNil(o.From) {
		var ret UpdateProjectTableCustomFieldRequestActionsInnerFrom
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetFromOk() (*UpdateProjectTableCustomFieldRequestActionsInnerFrom, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given UpdateProjectTableCustomFieldRequestActionsInnerFrom and assigns it to the From field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetFrom(v UpdateProjectTableCustomFieldRequestActionsInnerFrom) {
	o.From = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetValue(v string) {
	o.Value = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetValues(v []string) {
	o.Values = v
}

// GetValueMapJson returns the ValueMapJson field value if set, zero value otherwise.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValueMapJson() string {
	if o == nil || IsNil(o.ValueMapJson) {
		var ret string
		return ret
	}
	return *o.ValueMapJson
}

// GetValueMapJsonOk returns a tuple with the ValueMapJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) GetValueMapJsonOk() (*string, bool) {
	if o == nil || IsNil(o.ValueMapJson) {
		return nil, false
	}
	return o.ValueMapJson, true
}

// HasValueMapJson returns a boolean if a field has been set.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) HasValueMapJson() bool {
	if o != nil && !IsNil(o.ValueMapJson) {
		return true
	}

	return false
}

// SetValueMapJson gets a reference to the given string and assigns it to the ValueMapJson field.
func (o *UpdateProjectTableCustomFieldRequestActionsInner) SetValueMapJson(v string) {
	o.ValueMapJson = &v
}

func (o UpdateProjectTableCustomFieldRequestActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProjectTableCustomFieldRequestActionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.RowNumber) {
		toSerialize["rowNumber"] = o.RowNumber
	}
	if !IsNil(o.HeaderId) {
		toSerialize["headerId"] = o.HeaderId
	}
	if !IsNil(o.HeaderName) {
		toSerialize["headerName"] = o.HeaderName
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.ValueMapJson) {
		toSerialize["valueMapJson"] = o.ValueMapJson
	}
	return toSerialize, nil
}

type NullableUpdateProjectTableCustomFieldRequestActionsInner struct {
	value *UpdateProjectTableCustomFieldRequestActionsInner
	isSet bool
}

func (v NullableUpdateProjectTableCustomFieldRequestActionsInner) Get() *UpdateProjectTableCustomFieldRequestActionsInner {
	return v.value
}

func (v *NullableUpdateProjectTableCustomFieldRequestActionsInner) Set(val *UpdateProjectTableCustomFieldRequestActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProjectTableCustomFieldRequestActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProjectTableCustomFieldRequestActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProjectTableCustomFieldRequestActionsInner(val *UpdateProjectTableCustomFieldRequestActionsInner) *NullableUpdateProjectTableCustomFieldRequestActionsInner {
	return &NullableUpdateProjectTableCustomFieldRequestActionsInner{value: val, isSet: true}
}

func (v NullableUpdateProjectTableCustomFieldRequestActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProjectTableCustomFieldRequestActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


