/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner{}

// CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner 计划下一操作
type CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner struct {
	// 操作名称
	Name string `json:"name"`
	// 操作按钮颜色
	Color *string `json:"color,omitempty"`
	// 下一操作类型，enum ['action','link','iframe']
	Type string `json:"type"`
	// type = 'action'，设置此值，存储action内容 
	Value *string `json:"value,omitempty"`
	// type = 'link' 或 'iframe'时，设置此值，存储跳转链接地址
	Url string `json:"url"`
	// 挂载
	Payload interface{} `json:"payload,omitempty"`
}

// NewCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner instantiates a new CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner(name string, type_ string, url string) *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner {
	this := CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner{}
	this.Name = name
	this.Type = type_
	this.Url = url
	return &this
}

// NewCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInnerWithDefaults instantiates a new CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInnerWithDefaults() *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner {
	this := CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetName(v string) {
	o.Name = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetColor(v string) {
	o.Color = &v
}

// GetType returns the Type field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetValue(v string) {
	o.Value = &v
}

// GetUrl returns the Url field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetUrl(v string) {
	o.Url = v
}

// GetPayload returns the Payload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) HasPayload() bool {
	if o != nil && IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given interface{} and assigns it to the Payload field.
func (o *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) SetPayload(v interface{}) {
	o.Payload = v
}

func (o CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	toSerialize["url"] = o.Url
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner struct {
	value *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner
	isSet bool
}

func (v NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) Get() *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner {
	return v.value
}

func (v *NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) Set(val *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner(val *CreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) *NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner {
	return &NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner{value: val, isSet: true}
}

func (v NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectPlanStatusSettingV3RequestSettingCustomStatusInnerNextActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


