/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateCustomfieldV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomfieldV3Request{}

// UpdateCustomfieldV3Request struct for UpdateCustomfieldV3Request
type UpdateCustomfieldV3Request struct {
	// 字段名字
	Name *string `json:"name,omitempty"`
	// 字段类型, 仅支持 text => rtf 或者 dropdown => multipleChoice
	Type *string `json:"type,omitempty"`
	// 字段描述
	Description *string `json:"description,omitempty"`
	ExternalUrl *string `json:"externalUrl,omitempty"`
	Choices []CreateProjectCustomfieldV3RequestChoicesInner `json:"choices,omitempty"`
}

// NewUpdateCustomfieldV3Request instantiates a new UpdateCustomfieldV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomfieldV3Request() *UpdateCustomfieldV3Request {
	this := UpdateCustomfieldV3Request{}
	return &this
}

// NewUpdateCustomfieldV3RequestWithDefaults instantiates a new UpdateCustomfieldV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomfieldV3RequestWithDefaults() *UpdateCustomfieldV3Request {
	this := UpdateCustomfieldV3Request{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCustomfieldV3Request) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomfieldV3Request) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCustomfieldV3Request) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCustomfieldV3Request) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateCustomfieldV3Request) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomfieldV3Request) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateCustomfieldV3Request) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UpdateCustomfieldV3Request) SetType(v string) {
	o.Type = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateCustomfieldV3Request) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomfieldV3Request) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateCustomfieldV3Request) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateCustomfieldV3Request) SetDescription(v string) {
	o.Description = &v
}

// GetExternalUrl returns the ExternalUrl field value if set, zero value otherwise.
func (o *UpdateCustomfieldV3Request) GetExternalUrl() string {
	if o == nil || IsNil(o.ExternalUrl) {
		var ret string
		return ret
	}
	return *o.ExternalUrl
}

// GetExternalUrlOk returns a tuple with the ExternalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomfieldV3Request) GetExternalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalUrl) {
		return nil, false
	}
	return o.ExternalUrl, true
}

// HasExternalUrl returns a boolean if a field has been set.
func (o *UpdateCustomfieldV3Request) HasExternalUrl() bool {
	if o != nil && !IsNil(o.ExternalUrl) {
		return true
	}

	return false
}

// SetExternalUrl gets a reference to the given string and assigns it to the ExternalUrl field.
func (o *UpdateCustomfieldV3Request) SetExternalUrl(v string) {
	o.ExternalUrl = &v
}

// GetChoices returns the Choices field value if set, zero value otherwise.
func (o *UpdateCustomfieldV3Request) GetChoices() []CreateProjectCustomfieldV3RequestChoicesInner {
	if o == nil || IsNil(o.Choices) {
		var ret []CreateProjectCustomfieldV3RequestChoicesInner
		return ret
	}
	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomfieldV3Request) GetChoicesOk() ([]CreateProjectCustomfieldV3RequestChoicesInner, bool) {
	if o == nil || IsNil(o.Choices) {
		return nil, false
	}
	return o.Choices, true
}

// HasChoices returns a boolean if a field has been set.
func (o *UpdateCustomfieldV3Request) HasChoices() bool {
	if o != nil && !IsNil(o.Choices) {
		return true
	}

	return false
}

// SetChoices gets a reference to the given []CreateProjectCustomfieldV3RequestChoicesInner and assigns it to the Choices field.
func (o *UpdateCustomfieldV3Request) SetChoices(v []CreateProjectCustomfieldV3RequestChoicesInner) {
	o.Choices = v
}

func (o UpdateCustomfieldV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomfieldV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExternalUrl) {
		toSerialize["externalUrl"] = o.ExternalUrl
	}
	if !IsNil(o.Choices) {
		toSerialize["choices"] = o.Choices
	}
	return toSerialize, nil
}

type NullableUpdateCustomfieldV3Request struct {
	value *UpdateCustomfieldV3Request
	isSet bool
}

func (v NullableUpdateCustomfieldV3Request) Get() *UpdateCustomfieldV3Request {
	return v.value
}

func (v *NullableUpdateCustomfieldV3Request) Set(val *UpdateCustomfieldV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomfieldV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomfieldV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomfieldV3Request(val *UpdateCustomfieldV3Request) *NullableUpdateCustomfieldV3Request {
	return &NullableUpdateCustomfieldV3Request{value: val, isSet: true}
}

func (v NullableUpdateCustomfieldV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomfieldV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


