/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest{}

// PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest struct for PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest
type PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest struct {
	// 标签列表
	Labels []string `json:"labels,omitempty"`
	// 字段值列表
	Values []GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues `json:"values,omitempty"`
}

// NewPutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest instantiates a new PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest() *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest {
	this := PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest{}
	return &this
}

// NewPutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequestWithDefaults instantiates a new PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequestWithDefaults() *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest {
	this := PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) SetLabels(v []string) {
	o.Labels = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) GetValues() []GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues {
	if o == nil || IsNil(o.Values) {
		var ret []GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) GetValuesOk() ([]GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues and assigns it to the Values field.
func (o *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) SetValues(v []GetV3ProjectplanListscenariofieldvaluesResponseResultInnerValues) {
	o.Values = v
}

func (o PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest struct {
	value *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest
	isSet bool
}

func (v NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) Get() *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest {
	return v.value
}

func (v *NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) Set(val *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest(val *PutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) *NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest {
	return &NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest{value: val, isSet: true}
}

func (v NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutV3ProjectplanScenariofieldsUpdatescenariofieldvalueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


