/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PostV3ProgramUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3ProgramUpdateRequest{}

// PostV3ProgramUpdateRequest struct for PostV3ProgramUpdateRequest
type PostV3ProgramUpdateRequest struct {
	// 项目集名称
	Name *string `json:"name,omitempty"`
	// 项目集描述
	Description *string `json:"description,omitempty"`
	// 截止时间
	DueDate *time.Time `json:"dueDate,omitempty"`
	// 开始时间
	StartDate *time.Time `json:"startDate,omitempty"`
	// 项目集可见性
	Visible *string `json:"visible,omitempty"`
	// 项目集负责人 ID
	HolderId *string `json:"holderId,omitempty"`
}

// NewPostV3ProgramUpdateRequest instantiates a new PostV3ProgramUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3ProgramUpdateRequest() *PostV3ProgramUpdateRequest {
	this := PostV3ProgramUpdateRequest{}
	return &this
}

// NewPostV3ProgramUpdateRequestWithDefaults instantiates a new PostV3ProgramUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3ProgramUpdateRequestWithDefaults() *PostV3ProgramUpdateRequest {
	this := PostV3ProgramUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostV3ProgramUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PostV3ProgramUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetDueDate() time.Time {
	if o == nil || IsNil(o.DueDate) {
		var ret time.Time
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetDueDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given time.Time and assigns it to the DueDate field.
func (o *PostV3ProgramUpdateRequest) SetDueDate(v time.Time) {
	o.DueDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *PostV3ProgramUpdateRequest) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetVisible() string {
	if o == nil || IsNil(o.Visible) {
		var ret string
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetVisibleOk() (*string, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given string and assigns it to the Visible field.
func (o *PostV3ProgramUpdateRequest) SetVisible(v string) {
	o.Visible = &v
}

// GetHolderId returns the HolderId field value if set, zero value otherwise.
func (o *PostV3ProgramUpdateRequest) GetHolderId() string {
	if o == nil || IsNil(o.HolderId) {
		var ret string
		return ret
	}
	return *o.HolderId
}

// GetHolderIdOk returns a tuple with the HolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProgramUpdateRequest) GetHolderIdOk() (*string, bool) {
	if o == nil || IsNil(o.HolderId) {
		return nil, false
	}
	return o.HolderId, true
}

// HasHolderId returns a boolean if a field has been set.
func (o *PostV3ProgramUpdateRequest) HasHolderId() bool {
	if o != nil && !IsNil(o.HolderId) {
		return true
	}

	return false
}

// SetHolderId gets a reference to the given string and assigns it to the HolderId field.
func (o *PostV3ProgramUpdateRequest) SetHolderId(v string) {
	o.HolderId = &v
}

func (o PostV3ProgramUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3ProgramUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.HolderId) {
		toSerialize["holderId"] = o.HolderId
	}
	return toSerialize, nil
}

type NullablePostV3ProgramUpdateRequest struct {
	value *PostV3ProgramUpdateRequest
	isSet bool
}

func (v NullablePostV3ProgramUpdateRequest) Get() *PostV3ProgramUpdateRequest {
	return v.value
}

func (v *NullablePostV3ProgramUpdateRequest) Set(val *PostV3ProgramUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3ProgramUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3ProgramUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3ProgramUpdateRequest(val *PostV3ProgramUpdateRequest) *NullablePostV3ProgramUpdateRequest {
	return &NullablePostV3ProgramUpdateRequest{value: val, isSet: true}
}

func (v NullablePostV3ProgramUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3ProgramUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


