/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostV3ProjectplanCreatescenariofieldsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3ProjectplanCreatescenariofieldsRequest{}

// PostV3ProjectplanCreatescenariofieldsRequest struct for PostV3ProjectplanCreatescenariofieldsRequest
type PostV3ProjectplanCreatescenariofieldsRequest struct {
	// 字段列表
	Customfields []PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner `json:"customfields,omitempty"`
}

// NewPostV3ProjectplanCreatescenariofieldsRequest instantiates a new PostV3ProjectplanCreatescenariofieldsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3ProjectplanCreatescenariofieldsRequest() *PostV3ProjectplanCreatescenariofieldsRequest {
	this := PostV3ProjectplanCreatescenariofieldsRequest{}
	return &this
}

// NewPostV3ProjectplanCreatescenariofieldsRequestWithDefaults instantiates a new PostV3ProjectplanCreatescenariofieldsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3ProjectplanCreatescenariofieldsRequestWithDefaults() *PostV3ProjectplanCreatescenariofieldsRequest {
	this := PostV3ProjectplanCreatescenariofieldsRequest{}
	return &this
}

// GetCustomfields returns the Customfields field value if set, zero value otherwise.
func (o *PostV3ProjectplanCreatescenariofieldsRequest) GetCustomfields() []PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner {
	if o == nil || IsNil(o.Customfields) {
		var ret []PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner
		return ret
	}
	return o.Customfields
}

// GetCustomfieldsOk returns a tuple with the Customfields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanCreatescenariofieldsRequest) GetCustomfieldsOk() ([]PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner, bool) {
	if o == nil || IsNil(o.Customfields) {
		return nil, false
	}
	return o.Customfields, true
}

// HasCustomfields returns a boolean if a field has been set.
func (o *PostV3ProjectplanCreatescenariofieldsRequest) HasCustomfields() bool {
	if o != nil && !IsNil(o.Customfields) {
		return true
	}

	return false
}

// SetCustomfields gets a reference to the given []PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner and assigns it to the Customfields field.
func (o *PostV3ProjectplanCreatescenariofieldsRequest) SetCustomfields(v []PostV3ProjectplanCreatescenariofieldsRequestCustomfieldsInner) {
	o.Customfields = v
}

func (o PostV3ProjectplanCreatescenariofieldsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3ProjectplanCreatescenariofieldsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Customfields) {
		toSerialize["customfields"] = o.Customfields
	}
	return toSerialize, nil
}

type NullablePostV3ProjectplanCreatescenariofieldsRequest struct {
	value *PostV3ProjectplanCreatescenariofieldsRequest
	isSet bool
}

func (v NullablePostV3ProjectplanCreatescenariofieldsRequest) Get() *PostV3ProjectplanCreatescenariofieldsRequest {
	return v.value
}

func (v *NullablePostV3ProjectplanCreatescenariofieldsRequest) Set(val *PostV3ProjectplanCreatescenariofieldsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3ProjectplanCreatescenariofieldsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3ProjectplanCreatescenariofieldsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3ProjectplanCreatescenariofieldsRequest(val *PostV3ProjectplanCreatescenariofieldsRequest) *NullablePostV3ProjectplanCreatescenariofieldsRequest {
	return &NullablePostV3ProjectplanCreatescenariofieldsRequest{value: val, isSet: true}
}

func (v NullablePostV3ProjectplanCreatescenariofieldsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3ProjectplanCreatescenariofieldsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


