/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteProgramStatusCustomFieldV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteProgramStatusCustomFieldV3Request{}

// DeleteProgramStatusCustomFieldV3Request struct for DeleteProgramStatusCustomFieldV3Request
type DeleteProgramStatusCustomFieldV3Request struct {
	// 自定义字段 ID
	CustomfieldId *string `json:"customfieldId,omitempty"`
}

// NewDeleteProgramStatusCustomFieldV3Request instantiates a new DeleteProgramStatusCustomFieldV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteProgramStatusCustomFieldV3Request() *DeleteProgramStatusCustomFieldV3Request {
	this := DeleteProgramStatusCustomFieldV3Request{}
	return &this
}

// NewDeleteProgramStatusCustomFieldV3RequestWithDefaults instantiates a new DeleteProgramStatusCustomFieldV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteProgramStatusCustomFieldV3RequestWithDefaults() *DeleteProgramStatusCustomFieldV3Request {
	this := DeleteProgramStatusCustomFieldV3Request{}
	return &this
}

// GetCustomfieldId returns the CustomfieldId field value if set, zero value otherwise.
func (o *DeleteProgramStatusCustomFieldV3Request) GetCustomfieldId() string {
	if o == nil || IsNil(o.CustomfieldId) {
		var ret string
		return ret
	}
	return *o.CustomfieldId
}

// GetCustomfieldIdOk returns a tuple with the CustomfieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteProgramStatusCustomFieldV3Request) GetCustomfieldIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomfieldId) {
		return nil, false
	}
	return o.CustomfieldId, true
}

// HasCustomfieldId returns a boolean if a field has been set.
func (o *DeleteProgramStatusCustomFieldV3Request) HasCustomfieldId() bool {
	if o != nil && !IsNil(o.CustomfieldId) {
		return true
	}

	return false
}

// SetCustomfieldId gets a reference to the given string and assigns it to the CustomfieldId field.
func (o *DeleteProgramStatusCustomFieldV3Request) SetCustomfieldId(v string) {
	o.CustomfieldId = &v
}

func (o DeleteProgramStatusCustomFieldV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteProgramStatusCustomFieldV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomfieldId) {
		toSerialize["customfieldId"] = o.CustomfieldId
	}
	return toSerialize, nil
}

type NullableDeleteProgramStatusCustomFieldV3Request struct {
	value *DeleteProgramStatusCustomFieldV3Request
	isSet bool
}

func (v NullableDeleteProgramStatusCustomFieldV3Request) Get() *DeleteProgramStatusCustomFieldV3Request {
	return v.value
}

func (v *NullableDeleteProgramStatusCustomFieldV3Request) Set(val *DeleteProgramStatusCustomFieldV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteProgramStatusCustomFieldV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteProgramStatusCustomFieldV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteProgramStatusCustomFieldV3Request(val *DeleteProgramStatusCustomFieldV3Request) *NullableDeleteProgramStatusCustomFieldV3Request {
	return &NullableDeleteProgramStatusCustomFieldV3Request{value: val, isSet: true}
}

func (v NullableDeleteProgramStatusCustomFieldV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteProgramStatusCustomFieldV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


