/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PutV3TaskNodeUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutV3TaskNodeUpdateRequest{}

// PutV3TaskNodeUpdateRequest 更新任务节点
type PutV3TaskNodeUpdateRequest struct {
	// 任务节点ID
	NodeId *string `json:"nodeId,omitempty"`
	// 更新节点负责人ID列表
	AssigneeIds []string `json:"assigneeIds,omitempty"`
	// 更新计划开始时间
	StartDate NullableString `json:"startDate,omitempty"`
	// 更新计划截止时间
	DueDate NullableString `json:"dueDate,omitempty"`
	// 设置节点隐藏
	IsHidden *bool `json:"isHidden,omitempty"`
}

// NewPutV3TaskNodeUpdateRequest instantiates a new PutV3TaskNodeUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutV3TaskNodeUpdateRequest() *PutV3TaskNodeUpdateRequest {
	this := PutV3TaskNodeUpdateRequest{}
	return &this
}

// NewPutV3TaskNodeUpdateRequestWithDefaults instantiates a new PutV3TaskNodeUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutV3TaskNodeUpdateRequestWithDefaults() *PutV3TaskNodeUpdateRequest {
	this := PutV3TaskNodeUpdateRequest{}
	return &this
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *PutV3TaskNodeUpdateRequest) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutV3TaskNodeUpdateRequest) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *PutV3TaskNodeUpdateRequest) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *PutV3TaskNodeUpdateRequest) SetNodeId(v string) {
	o.NodeId = &v
}

// GetAssigneeIds returns the AssigneeIds field value if set, zero value otherwise.
func (o *PutV3TaskNodeUpdateRequest) GetAssigneeIds() []string {
	if o == nil || IsNil(o.AssigneeIds) {
		var ret []string
		return ret
	}
	return o.AssigneeIds
}

// GetAssigneeIdsOk returns a tuple with the AssigneeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutV3TaskNodeUpdateRequest) GetAssigneeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssigneeIds) {
		return nil, false
	}
	return o.AssigneeIds, true
}

// HasAssigneeIds returns a boolean if a field has been set.
func (o *PutV3TaskNodeUpdateRequest) HasAssigneeIds() bool {
	if o != nil && !IsNil(o.AssigneeIds) {
		return true
	}

	return false
}

// SetAssigneeIds gets a reference to the given []string and assigns it to the AssigneeIds field.
func (o *PutV3TaskNodeUpdateRequest) SetAssigneeIds(v []string) {
	o.AssigneeIds = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PutV3TaskNodeUpdateRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PutV3TaskNodeUpdateRequest) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *PutV3TaskNodeUpdateRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *PutV3TaskNodeUpdateRequest) SetStartDate(v string) {
	o.StartDate.Set(&v)
}
// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *PutV3TaskNodeUpdateRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *PutV3TaskNodeUpdateRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetDueDate returns the DueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PutV3TaskNodeUpdateRequest) GetDueDate() string {
	if o == nil || IsNil(o.DueDate.Get()) {
		var ret string
		return ret
	}
	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PutV3TaskNodeUpdateRequest) GetDueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// HasDueDate returns a boolean if a field has been set.
func (o *PutV3TaskNodeUpdateRequest) HasDueDate() bool {
	if o != nil && o.DueDate.IsSet() {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given NullableString and assigns it to the DueDate field.
func (o *PutV3TaskNodeUpdateRequest) SetDueDate(v string) {
	o.DueDate.Set(&v)
}
// SetDueDateNil sets the value for DueDate to be an explicit nil
func (o *PutV3TaskNodeUpdateRequest) SetDueDateNil() {
	o.DueDate.Set(nil)
}

// UnsetDueDate ensures that no value is present for DueDate, not even an explicit nil
func (o *PutV3TaskNodeUpdateRequest) UnsetDueDate() {
	o.DueDate.Unset()
}

// GetIsHidden returns the IsHidden field value if set, zero value otherwise.
func (o *PutV3TaskNodeUpdateRequest) GetIsHidden() bool {
	if o == nil || IsNil(o.IsHidden) {
		var ret bool
		return ret
	}
	return *o.IsHidden
}

// GetIsHiddenOk returns a tuple with the IsHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutV3TaskNodeUpdateRequest) GetIsHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHidden) {
		return nil, false
	}
	return o.IsHidden, true
}

// HasIsHidden returns a boolean if a field has been set.
func (o *PutV3TaskNodeUpdateRequest) HasIsHidden() bool {
	if o != nil && !IsNil(o.IsHidden) {
		return true
	}

	return false
}

// SetIsHidden gets a reference to the given bool and assigns it to the IsHidden field.
func (o *PutV3TaskNodeUpdateRequest) SetIsHidden(v bool) {
	o.IsHidden = &v
}

func (o PutV3TaskNodeUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutV3TaskNodeUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NodeId) {
		toSerialize["nodeId"] = o.NodeId
	}
	if !IsNil(o.AssigneeIds) {
		toSerialize["assigneeIds"] = o.AssigneeIds
	}
	if o.StartDate.IsSet() {
		toSerialize["startDate"] = o.StartDate.Get()
	}
	if o.DueDate.IsSet() {
		toSerialize["dueDate"] = o.DueDate.Get()
	}
	if !IsNil(o.IsHidden) {
		toSerialize["isHidden"] = o.IsHidden
	}
	return toSerialize, nil
}

type NullablePutV3TaskNodeUpdateRequest struct {
	value *PutV3TaskNodeUpdateRequest
	isSet bool
}

func (v NullablePutV3TaskNodeUpdateRequest) Get() *PutV3TaskNodeUpdateRequest {
	return v.value
}

func (v *NullablePutV3TaskNodeUpdateRequest) Set(val *PutV3TaskNodeUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutV3TaskNodeUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutV3TaskNodeUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutV3TaskNodeUpdateRequest(val *PutV3TaskNodeUpdateRequest) *NullablePutV3TaskNodeUpdateRequest {
	return &NullablePutV3TaskNodeUpdateRequest{value: val, isSet: true}
}

func (v NullablePutV3TaskNodeUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutV3TaskNodeUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


