/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetWorkspaceInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWorkspaceInfoResponse{}

// GetWorkspaceInfoResponse 
type GetWorkspaceInfoResponse struct {
	Result *GetWorkspaceInfoResponseResult `json:"result,omitempty"`
	// 响应状态码
	Code *float32 `json:"code,omitempty"`
	// 异常错误信息
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// 请求 ID，请求异常时可提供此 ID，进行问题排查。
	RequestId *string `json:"requestId,omitempty"`
}

// NewGetWorkspaceInfoResponse instantiates a new GetWorkspaceInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkspaceInfoResponse() *GetWorkspaceInfoResponse {
	this := GetWorkspaceInfoResponse{}
	return &this
}

// NewGetWorkspaceInfoResponseWithDefaults instantiates a new GetWorkspaceInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkspaceInfoResponseWithDefaults() *GetWorkspaceInfoResponse {
	this := GetWorkspaceInfoResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetWorkspaceInfoResponse) GetResult() GetWorkspaceInfoResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret GetWorkspaceInfoResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkspaceInfoResponse) GetResultOk() (*GetWorkspaceInfoResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetWorkspaceInfoResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GetWorkspaceInfoResponseResult and assigns it to the Result field.
func (o *GetWorkspaceInfoResponse) SetResult(v GetWorkspaceInfoResponseResult) {
	o.Result = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetWorkspaceInfoResponse) GetCode() float32 {
	if o == nil || IsNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkspaceInfoResponse) GetCodeOk() (*float32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetWorkspaceInfoResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *GetWorkspaceInfoResponse) SetCode(v float32) {
	o.Code = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *GetWorkspaceInfoResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkspaceInfoResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *GetWorkspaceInfoResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *GetWorkspaceInfoResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetWorkspaceInfoResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkspaceInfoResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetWorkspaceInfoResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetWorkspaceInfoResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GetWorkspaceInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWorkspaceInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableGetWorkspaceInfoResponse struct {
	value *GetWorkspaceInfoResponse
	isSet bool
}

func (v NullableGetWorkspaceInfoResponse) Get() *GetWorkspaceInfoResponse {
	return v.value
}

func (v *NullableGetWorkspaceInfoResponse) Set(val *GetWorkspaceInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkspaceInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkspaceInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkspaceInfoResponse(val *GetWorkspaceInfoResponse) *NullableGetWorkspaceInfoResponse {
	return &NullableGetWorkspaceInfoResponse{value: val, isSet: true}
}

func (v NullableGetWorkspaceInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkspaceInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


