/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateTaskLockV3RequestAddInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTaskLockV3RequestAddInner{}

// UpdateTaskLockV3RequestAddInner struct for UpdateTaskLockV3RequestAddInner
type UpdateTaskLockV3RequestAddInner struct {
	// 锁定动作, 可选值： - `content$update`: 更新任务标题 - `executorId$update`: 更新执行者 - `startDate$update`: 更新开始时间 - `dueDate$update`: 更新截止时间 - `effort$update`: 更新投入时间 - `note$update`: 更新备注 - `priority$update`: 更新优先级 - `storyPoint$update`: 更新storyPoint - `progress$update`: 更新进展 - `tagIds$update`: 更新标签 - `task$archive`: 删除任务 - `cf:${string}$update`: 更新自定义字段值，${string}为自定义字段ID 
	Action *string `json:"action,omitempty"`
}

// NewUpdateTaskLockV3RequestAddInner instantiates a new UpdateTaskLockV3RequestAddInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTaskLockV3RequestAddInner() *UpdateTaskLockV3RequestAddInner {
	this := UpdateTaskLockV3RequestAddInner{}
	return &this
}

// NewUpdateTaskLockV3RequestAddInnerWithDefaults instantiates a new UpdateTaskLockV3RequestAddInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTaskLockV3RequestAddInnerWithDefaults() *UpdateTaskLockV3RequestAddInner {
	this := UpdateTaskLockV3RequestAddInner{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *UpdateTaskLockV3RequestAddInner) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTaskLockV3RequestAddInner) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *UpdateTaskLockV3RequestAddInner) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *UpdateTaskLockV3RequestAddInner) SetAction(v string) {
	o.Action = &v
}

func (o UpdateTaskLockV3RequestAddInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTaskLockV3RequestAddInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	return toSerialize, nil
}

type NullableUpdateTaskLockV3RequestAddInner struct {
	value *UpdateTaskLockV3RequestAddInner
	isSet bool
}

func (v NullableUpdateTaskLockV3RequestAddInner) Get() *UpdateTaskLockV3RequestAddInner {
	return v.value
}

func (v *NullableUpdateTaskLockV3RequestAddInner) Set(val *UpdateTaskLockV3RequestAddInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTaskLockV3RequestAddInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTaskLockV3RequestAddInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTaskLockV3RequestAddInner(val *UpdateTaskLockV3RequestAddInner) *NullableUpdateTaskLockV3RequestAddInner {
	return &NullableUpdateTaskLockV3RequestAddInner{value: val, isSet: true}
}

func (v NullableUpdateTaskLockV3RequestAddInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTaskLockV3RequestAddInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


