/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchFieldCategoriesV3Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchFieldCategoriesV3Response{}

// SearchFieldCategoriesV3Response struct for SearchFieldCategoriesV3Response
type SearchFieldCategoriesV3Response struct {
	// 任务类型列表
	Result []SearchFieldCategoriesV3ResponseResultInner `json:"result,omitempty"`
	// 分页标
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// 响应状态码
	Code *float32 `json:"code,omitempty"`
	// 异常错误信息
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// 请求 ID，请求异常时可提供此 ID，进行问题排查。
	RequestId *string `json:"requestId,omitempty"`
}

// NewSearchFieldCategoriesV3Response instantiates a new SearchFieldCategoriesV3Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchFieldCategoriesV3Response() *SearchFieldCategoriesV3Response {
	this := SearchFieldCategoriesV3Response{}
	return &this
}

// NewSearchFieldCategoriesV3ResponseWithDefaults instantiates a new SearchFieldCategoriesV3Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchFieldCategoriesV3ResponseWithDefaults() *SearchFieldCategoriesV3Response {
	this := SearchFieldCategoriesV3Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *SearchFieldCategoriesV3Response) GetResult() []SearchFieldCategoriesV3ResponseResultInner {
	if o == nil || IsNil(o.Result) {
		var ret []SearchFieldCategoriesV3ResponseResultInner
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFieldCategoriesV3Response) GetResultOk() ([]SearchFieldCategoriesV3ResponseResultInner, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *SearchFieldCategoriesV3Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []SearchFieldCategoriesV3ResponseResultInner and assigns it to the Result field.
func (o *SearchFieldCategoriesV3Response) SetResult(v []SearchFieldCategoriesV3ResponseResultInner) {
	o.Result = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *SearchFieldCategoriesV3Response) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFieldCategoriesV3Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *SearchFieldCategoriesV3Response) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *SearchFieldCategoriesV3Response) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SearchFieldCategoriesV3Response) GetCode() float32 {
	if o == nil || IsNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFieldCategoriesV3Response) GetCodeOk() (*float32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SearchFieldCategoriesV3Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *SearchFieldCategoriesV3Response) SetCode(v float32) {
	o.Code = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *SearchFieldCategoriesV3Response) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFieldCategoriesV3Response) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *SearchFieldCategoriesV3Response) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *SearchFieldCategoriesV3Response) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *SearchFieldCategoriesV3Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFieldCategoriesV3Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *SearchFieldCategoriesV3Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *SearchFieldCategoriesV3Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o SearchFieldCategoriesV3Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchFieldCategoriesV3Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableSearchFieldCategoriesV3Response struct {
	value *SearchFieldCategoriesV3Response
	isSet bool
}

func (v NullableSearchFieldCategoriesV3Response) Get() *SearchFieldCategoriesV3Response {
	return v.value
}

func (v *NullableSearchFieldCategoriesV3Response) Set(val *SearchFieldCategoriesV3Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchFieldCategoriesV3Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchFieldCategoriesV3Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchFieldCategoriesV3Response(val *SearchFieldCategoriesV3Response) *NullableSearchFieldCategoriesV3Response {
	return &NullableSearchFieldCategoriesV3Response{value: val, isSet: true}
}

func (v NullableSearchFieldCategoriesV3Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchFieldCategoriesV3Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


