/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdatePipelineParamsRequestBuildParamsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePipelineParamsRequestBuildParamsInner{}

// UpdatePipelineParamsRequestBuildParamsInner struct for UpdatePipelineParamsRequestBuildParamsInner
type UpdatePipelineParamsRequestBuildParamsInner struct {
	// 参数名称
	Name string `json:"name"`
	// 参数类型，目前支持字符串(string)、布尔(bool)、单选(choice)，其他类型传 unSupport
	Type string `json:"type"`
	// 参数描述
	Description *string `json:"description,omitempty"`
	DefaultValue *UpdatePipelineParamsRequestBuildParamsInnerDefaultValue `json:"defaultValue,omitempty"`
	// choice类型时必传，可选信息
	Choices []UpdatePipelineParamsRequestBuildParamsInnerChoicesInner `json:"choices,omitempty"`
}

// NewUpdatePipelineParamsRequestBuildParamsInner instantiates a new UpdatePipelineParamsRequestBuildParamsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePipelineParamsRequestBuildParamsInner(name string, type_ string) *UpdatePipelineParamsRequestBuildParamsInner {
	this := UpdatePipelineParamsRequestBuildParamsInner{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewUpdatePipelineParamsRequestBuildParamsInnerWithDefaults instantiates a new UpdatePipelineParamsRequestBuildParamsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePipelineParamsRequestBuildParamsInnerWithDefaults() *UpdatePipelineParamsRequestBuildParamsInner {
	this := UpdatePipelineParamsRequestBuildParamsInner{}
	return &this
}

// GetName returns the Name field value
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdatePipelineParamsRequestBuildParamsInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdatePipelineParamsRequestBuildParamsInner) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdatePipelineParamsRequestBuildParamsInner) SetDescription(v string) {
	o.Description = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetDefaultValue() UpdatePipelineParamsRequestBuildParamsInnerDefaultValue {
	if o == nil || IsNil(o.DefaultValue) {
		var ret UpdatePipelineParamsRequestBuildParamsInnerDefaultValue
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetDefaultValueOk() (*UpdatePipelineParamsRequestBuildParamsInnerDefaultValue, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given UpdatePipelineParamsRequestBuildParamsInnerDefaultValue and assigns it to the DefaultValue field.
func (o *UpdatePipelineParamsRequestBuildParamsInner) SetDefaultValue(v UpdatePipelineParamsRequestBuildParamsInnerDefaultValue) {
	o.DefaultValue = &v
}

// GetChoices returns the Choices field value if set, zero value otherwise.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetChoices() []UpdatePipelineParamsRequestBuildParamsInnerChoicesInner {
	if o == nil || IsNil(o.Choices) {
		var ret []UpdatePipelineParamsRequestBuildParamsInnerChoicesInner
		return ret
	}
	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) GetChoicesOk() ([]UpdatePipelineParamsRequestBuildParamsInnerChoicesInner, bool) {
	if o == nil || IsNil(o.Choices) {
		return nil, false
	}
	return o.Choices, true
}

// HasChoices returns a boolean if a field has been set.
func (o *UpdatePipelineParamsRequestBuildParamsInner) HasChoices() bool {
	if o != nil && !IsNil(o.Choices) {
		return true
	}

	return false
}

// SetChoices gets a reference to the given []UpdatePipelineParamsRequestBuildParamsInnerChoicesInner and assigns it to the Choices field.
func (o *UpdatePipelineParamsRequestBuildParamsInner) SetChoices(v []UpdatePipelineParamsRequestBuildParamsInnerChoicesInner) {
	o.Choices = v
}

func (o UpdatePipelineParamsRequestBuildParamsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePipelineParamsRequestBuildParamsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.Choices) {
		toSerialize["choices"] = o.Choices
	}
	return toSerialize, nil
}

type NullableUpdatePipelineParamsRequestBuildParamsInner struct {
	value *UpdatePipelineParamsRequestBuildParamsInner
	isSet bool
}

func (v NullableUpdatePipelineParamsRequestBuildParamsInner) Get() *UpdatePipelineParamsRequestBuildParamsInner {
	return v.value
}

func (v *NullableUpdatePipelineParamsRequestBuildParamsInner) Set(val *UpdatePipelineParamsRequestBuildParamsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePipelineParamsRequestBuildParamsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePipelineParamsRequestBuildParamsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePipelineParamsRequestBuildParamsInner(val *UpdatePipelineParamsRequestBuildParamsInner) *NullableUpdatePipelineParamsRequestBuildParamsInner {
	return &NullableUpdatePipelineParamsRequestBuildParamsInner{value: val, isSet: true}
}

func (v NullableUpdatePipelineParamsRequestBuildParamsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePipelineParamsRequestBuildParamsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


