/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateProjectV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectV3Request{}

// CreateProjectV3Request 创建项目请求
type CreateProjectV3Request struct {
	// 项目名称
	Name *string `json:"name,omitempty"`
}

// NewCreateProjectV3Request instantiates a new CreateProjectV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectV3Request() *CreateProjectV3Request {
	this := CreateProjectV3Request{}
	return &this
}

// NewCreateProjectV3RequestWithDefaults instantiates a new CreateProjectV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectV3RequestWithDefaults() *CreateProjectV3Request {
	this := CreateProjectV3Request{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateProjectV3Request) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectV3Request) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateProjectV3Request) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateProjectV3Request) SetName(v string) {
	o.Name = &v
}

func (o CreateProjectV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateProjectV3Request struct {
	value *CreateProjectV3Request
	isSet bool
}

func (v NullableCreateProjectV3Request) Get() *CreateProjectV3Request {
	return v.value
}

func (v *NullableCreateProjectV3Request) Set(val *CreateProjectV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectV3Request(val *CreateProjectV3Request) *NullableCreateProjectV3Request {
	return &NullableCreateProjectV3Request{value: val, isSet: true}
}

func (v NullableCreateProjectV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


