/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostV3ProjectplanProjectPlansRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3ProjectplanProjectPlansRequest{}

// PostV3ProjectplanProjectPlansRequest struct for PostV3ProjectplanProjectPlansRequest
type PostV3ProjectplanProjectPlansRequest struct {
	// 计划名称
	Subject *string `json:"subject,omitempty"`
	// 计划开始时间, 空字符串 代表清空
	StartDate *string `json:"startDate,omitempty"`
	// 计划结束时间, 空字符串 代表清空
	DueDate *string `json:"dueDate,omitempty"`
	// 父计划ID
	ParentId *string `json:"parentId,omitempty"`
	// 计划负责人
	OwnerIds []string `json:"ownerIds,omitempty"`
	// 计划参与者
	ParticipantIds []string `json:"participantIds,omitempty"`
	// 计划可见范围,enum['involves', 'project']
	Visible *string `json:"visible,omitempty"`
	MemberSyncRule *PostV3ProjectplanProjectPlansRequestMemberSyncRule `json:"memberSyncRule,omitempty"`
}

// NewPostV3ProjectplanProjectPlansRequest instantiates a new PostV3ProjectplanProjectPlansRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3ProjectplanProjectPlansRequest() *PostV3ProjectplanProjectPlansRequest {
	this := PostV3ProjectplanProjectPlansRequest{}
	return &this
}

// NewPostV3ProjectplanProjectPlansRequestWithDefaults instantiates a new PostV3ProjectplanProjectPlansRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3ProjectplanProjectPlansRequestWithDefaults() *PostV3ProjectplanProjectPlansRequest {
	this := PostV3ProjectplanProjectPlansRequest{}
	return &this
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *PostV3ProjectplanProjectPlansRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *PostV3ProjectplanProjectPlansRequest) SetStartDate(v string) {
	o.StartDate = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *PostV3ProjectplanProjectPlansRequest) SetDueDate(v string) {
	o.DueDate = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *PostV3ProjectplanProjectPlansRequest) SetParentId(v string) {
	o.ParentId = &v
}

// GetOwnerIds returns the OwnerIds field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetOwnerIds() []string {
	if o == nil || IsNil(o.OwnerIds) {
		var ret []string
		return ret
	}
	return o.OwnerIds
}

// GetOwnerIdsOk returns a tuple with the OwnerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetOwnerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.OwnerIds) {
		return nil, false
	}
	return o.OwnerIds, true
}

// HasOwnerIds returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasOwnerIds() bool {
	if o != nil && !IsNil(o.OwnerIds) {
		return true
	}

	return false
}

// SetOwnerIds gets a reference to the given []string and assigns it to the OwnerIds field.
func (o *PostV3ProjectplanProjectPlansRequest) SetOwnerIds(v []string) {
	o.OwnerIds = v
}

// GetParticipantIds returns the ParticipantIds field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetParticipantIds() []string {
	if o == nil || IsNil(o.ParticipantIds) {
		var ret []string
		return ret
	}
	return o.ParticipantIds
}

// GetParticipantIdsOk returns a tuple with the ParticipantIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetParticipantIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ParticipantIds) {
		return nil, false
	}
	return o.ParticipantIds, true
}

// HasParticipantIds returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasParticipantIds() bool {
	if o != nil && !IsNil(o.ParticipantIds) {
		return true
	}

	return false
}

// SetParticipantIds gets a reference to the given []string and assigns it to the ParticipantIds field.
func (o *PostV3ProjectplanProjectPlansRequest) SetParticipantIds(v []string) {
	o.ParticipantIds = v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetVisible() string {
	if o == nil || IsNil(o.Visible) {
		var ret string
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetVisibleOk() (*string, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given string and assigns it to the Visible field.
func (o *PostV3ProjectplanProjectPlansRequest) SetVisible(v string) {
	o.Visible = &v
}

// GetMemberSyncRule returns the MemberSyncRule field value if set, zero value otherwise.
func (o *PostV3ProjectplanProjectPlansRequest) GetMemberSyncRule() PostV3ProjectplanProjectPlansRequestMemberSyncRule {
	if o == nil || IsNil(o.MemberSyncRule) {
		var ret PostV3ProjectplanProjectPlansRequestMemberSyncRule
		return ret
	}
	return *o.MemberSyncRule
}

// GetMemberSyncRuleOk returns a tuple with the MemberSyncRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV3ProjectplanProjectPlansRequest) GetMemberSyncRuleOk() (*PostV3ProjectplanProjectPlansRequestMemberSyncRule, bool) {
	if o == nil || IsNil(o.MemberSyncRule) {
		return nil, false
	}
	return o.MemberSyncRule, true
}

// HasMemberSyncRule returns a boolean if a field has been set.
func (o *PostV3ProjectplanProjectPlansRequest) HasMemberSyncRule() bool {
	if o != nil && !IsNil(o.MemberSyncRule) {
		return true
	}

	return false
}

// SetMemberSyncRule gets a reference to the given PostV3ProjectplanProjectPlansRequestMemberSyncRule and assigns it to the MemberSyncRule field.
func (o *PostV3ProjectplanProjectPlansRequest) SetMemberSyncRule(v PostV3ProjectplanProjectPlansRequestMemberSyncRule) {
	o.MemberSyncRule = &v
}

func (o PostV3ProjectplanProjectPlansRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3ProjectplanProjectPlansRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	if !IsNil(o.OwnerIds) {
		toSerialize["ownerIds"] = o.OwnerIds
	}
	if !IsNil(o.ParticipantIds) {
		toSerialize["participantIds"] = o.ParticipantIds
	}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.MemberSyncRule) {
		toSerialize["memberSyncRule"] = o.MemberSyncRule
	}
	return toSerialize, nil
}

type NullablePostV3ProjectplanProjectPlansRequest struct {
	value *PostV3ProjectplanProjectPlansRequest
	isSet bool
}

func (v NullablePostV3ProjectplanProjectPlansRequest) Get() *PostV3ProjectplanProjectPlansRequest {
	return v.value
}

func (v *NullablePostV3ProjectplanProjectPlansRequest) Set(val *PostV3ProjectplanProjectPlansRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3ProjectplanProjectPlansRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3ProjectplanProjectPlansRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3ProjectplanProjectPlansRequest(val *PostV3ProjectplanProjectPlansRequest) *NullablePostV3ProjectplanProjectPlansRequest {
	return &NullablePostV3ProjectplanProjectPlansRequest{value: val, isSet: true}
}

func (v NullablePostV3ProjectplanProjectPlansRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3ProjectplanProjectPlansRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


