/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddProgramProjectsV3Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddProgramProjectsV3Request{}

// AddProgramProjectsV3Request struct for AddProgramProjectsV3Request
type AddProgramProjectsV3Request struct {
	// 项目 ID 列表
	ProjectIds []string `json:"projectIds,omitempty"`
}

// NewAddProgramProjectsV3Request instantiates a new AddProgramProjectsV3Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddProgramProjectsV3Request() *AddProgramProjectsV3Request {
	this := AddProgramProjectsV3Request{}
	return &this
}

// NewAddProgramProjectsV3RequestWithDefaults instantiates a new AddProgramProjectsV3Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddProgramProjectsV3RequestWithDefaults() *AddProgramProjectsV3Request {
	this := AddProgramProjectsV3Request{}
	return &this
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise.
func (o *AddProgramProjectsV3Request) GetProjectIds() []string {
	if o == nil || IsNil(o.ProjectIds) {
		var ret []string
		return ret
	}
	return o.ProjectIds
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddProgramProjectsV3Request) GetProjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectIds) {
		return nil, false
	}
	return o.ProjectIds, true
}

// HasProjectIds returns a boolean if a field has been set.
func (o *AddProgramProjectsV3Request) HasProjectIds() bool {
	if o != nil && !IsNil(o.ProjectIds) {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given []string and assigns it to the ProjectIds field.
func (o *AddProgramProjectsV3Request) SetProjectIds(v []string) {
	o.ProjectIds = v
}

func (o AddProgramProjectsV3Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddProgramProjectsV3Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectIds) {
		toSerialize["projectIds"] = o.ProjectIds
	}
	return toSerialize, nil
}

type NullableAddProgramProjectsV3Request struct {
	value *AddProgramProjectsV3Request
	isSet bool
}

func (v NullableAddProgramProjectsV3Request) Get() *AddProgramProjectsV3Request {
	return v.value
}

func (v *NullableAddProgramProjectsV3Request) Set(val *AddProgramProjectsV3Request) {
	v.value = val
	v.isSet = true
}

func (v NullableAddProgramProjectsV3Request) IsSet() bool {
	return v.isSet
}

func (v *NullableAddProgramProjectsV3Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddProgramProjectsV3Request(val *AddProgramProjectsV3Request) *NullableAddProgramProjectsV3Request {
	return &NullableAddProgramProjectsV3Request{value: val, isSet: true}
}

func (v NullableAddProgramProjectsV3Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddProgramProjectsV3Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


