/*
Teambition Open API

Teambition Open API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListGroupMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGroupMembersResponse{}

// ListGroupMembersResponse struct for ListGroupMembersResponse
type ListGroupMembersResponse struct {
	// 分页标记，当返回为非空字符串时表示还有更多数据，可以将此字符串赋值到请求参数 pageToken 获取更多数据。示例值：\"cfcbh8noe9jct71bqkg0\"
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// 本次请求条件下的数据总量
	Count *float32 `json:"count,omitempty"`
	Result []ListGroupMembersResponseResultInner `json:"result,omitempty"`
	// 响应状态码
	Code *float32 `json:"code,omitempty"`
	// 异常错误信息
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// 请求 ID，请求异常时可提供此 ID，进行问题排查。
	RequestId *string `json:"requestId,omitempty"`
}

// NewListGroupMembersResponse instantiates a new ListGroupMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGroupMembersResponse() *ListGroupMembersResponse {
	this := ListGroupMembersResponse{}
	return &this
}

// NewListGroupMembersResponseWithDefaults instantiates a new ListGroupMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGroupMembersResponseWithDefaults() *ListGroupMembersResponse {
	this := ListGroupMembersResponse{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListGroupMembersResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetCount() float32 {
	if o == nil || IsNil(o.Count) {
		var ret float32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetCountOk() (*float32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given float32 and assigns it to the Count field.
func (o *ListGroupMembersResponse) SetCount(v float32) {
	o.Count = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetResult() []ListGroupMembersResponseResultInner {
	if o == nil || IsNil(o.Result) {
		var ret []ListGroupMembersResponseResultInner
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetResultOk() ([]ListGroupMembersResponseResultInner, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []ListGroupMembersResponseResultInner and assigns it to the Result field.
func (o *ListGroupMembersResponse) SetResult(v []ListGroupMembersResponseResultInner) {
	o.Result = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetCode() float32 {
	if o == nil || IsNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetCodeOk() (*float32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *ListGroupMembersResponse) SetCode(v float32) {
	o.Code = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ListGroupMembersResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ListGroupMembersResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupMembersResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ListGroupMembersResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ListGroupMembersResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o ListGroupMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGroupMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableListGroupMembersResponse struct {
	value *ListGroupMembersResponse
	isSet bool
}

func (v NullableListGroupMembersResponse) Get() *ListGroupMembersResponse {
	return v.value
}

func (v *NullableListGroupMembersResponse) Set(val *ListGroupMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListGroupMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListGroupMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGroupMembersResponse(val *ListGroupMembersResponse) *NullableListGroupMembersResponse {
	return &NullableListGroupMembersResponse{value: val, isSet: true}
}

func (v NullableListGroupMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGroupMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


